version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 048069023324.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t brain-task .
      - docker tag brain-task:latest 048069023324.dkr.ecr.ap-south-1.amazonaws.com/brain-task:latest

  post_build:
    commands:
      - docker push 048069023324.dkr.ecr.ap-south-1.amazonaws.com/brain-task:latest
