apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainmindtask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brainmindtask
  template:
    metadata:
      labels:
        app: brainmindtask
    spec:
      containers:
      - name: brainmindtask
        image: 048069023324.dkr.ecr.ap-south-1.amazonaws.com/brain-task:latest
        ports:
        - containerPort: 80