apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainmindtask-deployment
  labels:
    app: brainmindtask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brainmindtask
  template:
    metadata:
      labels:
        app: brainmindtask
    spec:
      containers:
      - name: brainmindtask
        image: 518299480869.dkr.ecr.ap-south-2.amazonaws.com/brainmindtask:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000