apiVersion: v1
kind: Service
metadata:
  name: brainmindtask-service
spec:
  selector:
    app: brainmindtask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer